### ISSUE TITLE
Улучшить скорость загрузки сайта

### ISSUE THREAD

**Issue by Yogik10** [Vld9117/dimap#12]
На данный момент (бутстрап + jpg):
https://loading.express/?test_id=61315451b89188604f9d33f8&server=main
![image](https://user-images.githubusercontent.com/42892474/131927125-9f3a3408-3b2b-450d-81c7-054229637e41.png)
![image](https://user-images.githubusercontent.com/42892474/131927141-21cc0425-e7c5-4033-8df6-a265c0aa5785.png)
![image](https://user-images.githubusercontent.com/42892474/131927152-86e2f0b9-08f6-47f4-bf23-3b3343ddf631.png)

**Comment by Vld9117** [comment]
Есть ли средство последовательной загрузки,
т.е. не ждать полной загрузки сайта,
а предоставить право сайту загружать элементы медленно.
#задачка

**Comment by Vld9117** [comment]
![image](https://user-images.githubusercontent.com/78636632/132122985-499aa5d7-b797-4ca0-a3bb-538eda476b25.png)

**Comment by Vld9117** [comment]
Немного быстрее
![image](https://user-images.githubusercontent.com/78636632/132123283-e82684ad-ffa2-4037-9537-849f50497c60.png)

**Comment by Vld9117** [comment]
Ещё чуть лучше
![image](https://user-images.githubusercontent.com/78636632/132123610-754230fc-2e94-4850-937a-bdaf5315d847.png)

**Comment by Vld9117** [comment]
Дошли до 8/10))

![image](https://user-images.githubusercontent.com/78636632/132124940-17bfb37e-55fb-4bbc-955a-fb91b2b8926c.png)

**Comment by Vld9117** [comment]
> На данный момент (бутстрап + jpg):
> https://loading.express/?test_id=61315451b89188604f9d33f8&server=main
> ![image](https://user-images.githubusercontent.com/42892474/131927125-9f3a3408-3b2b-450d-81c7-054229637e41.png)
> ![image](https://user-images.githubusercontent.com/42892474/131927141-21cc0425-e7c5-4033-8df6-a265c0aa5785.png)
> ![image](https://user-images.githubusercontent.com/42892474/131927152-86e2f0b9-08f6-47f4-bf23-3b3343ddf631.png)

![image](https://user-images.githubusercontent.com/78636632/132125001-8bf4a33f-c9e9-4c42-a3cb-1e9eccde6050.png)

**Comment by Yogik10** [comment]
Сделано, я считаю
